wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/Wallpapers/mathias-reding-U-tAamokJ9I-unsplash.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/peter-lloyd-rRWyOn9gat4-unsplash.jpg
    fit_mode = cover
}
