wallpaper {
    monitor = HDMI-A-2
    path = /home/ouroboros/Pictures/Wallpapers/arnab-pradhan-z6wW-YTNAbM-unsplash.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/ouroboros/Pictures/Wallpapers/peter-lloyd-rRWyOn9gat4-unsplash.jpg
    fit_mode = cover
}
